#!/bin/sh
OS="$(uname -s)"
ARCH="$(uname -m | sed -e s/i.86/x86/ -e s/x86_64/x86/ -e s/amd64/x86/ \
                       -e s/sun4u/sparc64/ \
                       -e s/arm.*/arm/ -e s/sa110/arm/ \
                       -e s/s390x/s390/ -e s/parisc64/parisc/ \
                       -e s/ppc.*/powerpc/ -e s/mips.*/mips/ \
                       -e s/sh[234].*/sh/ -e s/aarch64.*/arm64/)"
BIT="$(getconf LONG_BIT)"
COMMAND="${0}-${OS}-${ARCH}-${BIT}"

if [ -e $COMMAND ]; then
    exec $COMMAND
else
    echo "Command ${COMMAND} not found."
    echo "Unsupported architecture ${OS} ${ARCH} ${BIT}"
fi
