#!/bin/sh
# -*- coding: utf-8 -*-
#  Copyright (C) 2014 Yusuke Suzuki <utatane.tea@gmail.com>
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
#  DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
#  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
#  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
#  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
#  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

OS="$(\uname -s)"
ARCH="$(\uname -m | \sed -e s/i.86/x86/ -e s/x86_64/x86/ -e s/amd64/x86/ \
                         -e s/sun4u/sparc64/ \
                         -e s/arm.*/arm/ -e s/sa110/arm/ \
                         -e s/s390x/s390/ -e s/parisc64/parisc/ \
                         -e s/ppc.*/powerpc/ -e s/mips.*/mips/ \
                         -e s/sh[234].*/sh/ -e s/aarch64.*/arm64/)"
BIT="$(\getconf LONG_BIT)"

case "$OS" in
    Linux)
        TARGET="$(\readlink -f "${0}")"
        ;;
    *)
        if hash greadlink 2>/dev/null; then
            TARGET="$(\greadlink "${0}")"
        else
            echo "GNU readlink command is needed."
            exit 1
        fi
        ;;
esac
DIR="$(dirname ${TARGET})"
BASENAME="$(basename "${0}")"
COMMAND="${DIR}/${BASENAME}-${OS}-${ARCH}-${BIT}"

if [ -e $COMMAND ]; then
    exec $COMMAND
else
    echo "Command ${COMMAND} not found."
    echo "Unsupported architecture ${OS} ${ARCH} ${BIT}"
    exit 1
fi
